---
title: Innlevering 3
author: Innlevering 3 i Data Science 2021 - Maren Sognefest og Daniel Karstad
Affiliation: HVL
email: 152148@stud.hvl.no & 598289@stud.hvl.no
bibliography: 
bib-humanities: true
nocite: 
lang: no-NB
fontsize: 12pt
linestretch: 1.5
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
  html_notebook: default
---
```{r echo=FALSE}
library(styler) 
library(gapminder)
```

# 1
Filen ddf_concepts.csv inneholder forskjellig informasjon om de ulike variablene i datasettene. Disse variablene omhandler mye forskjellig, blant annet hvor mange som har hiv, hvor mange som har mobiltelefon, hvor mange som har ulike typer kreft osv. 


# 2
Filen ddf--entities--geo--country.csv inneholder informasjon om alle verdens land. Det er mye ulik informasjon, blant annet hvor mye befolkningen tjener, hvilken religion landet tilhører, hvorvidt landet er et utviklingsland, hvilken verdensdel det ligger i osv.


# 3 
Filen ddf--entitites--geo--un_sdg_region.csv inneholder en liste over verdens regioner og om hvorvidt disse er med i FN. 


# 4
Pakken *gapminder* inneholder blant annet et datasett som heter *Gapminder*. Dette inneholder variablene "land" (country), "kontinent" (countinent), "år" (year), "forventet levetid" (lifeExp), "befolkning" (pop) og "GDP per capita" (gdpPercap, i dollar. Er justert etter inflasjon). I dette datasettet står det at Australig og New Zealand er i Oseania.


# 5

Recreate thecontinentvariable in gapminder with the new data (Hint! Move Australia and NewZealand from Asia to Oceania). Only include countries that have aiso3166_1_alpha3code. Use datafromddf--entities--geo--country.csvand call this tibbleg_c. Letg_cbe your main tibble in thefollowing, i.e. add variables to this tibble.

6. How many countries are there now? The functionsunique()andlength()might be of some help.

## [1] 2476. How many countries are there now in each continent?## # A tibble: 5 x 2## # Groups:   continent [5]##   continent numbe
